# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
# app: cron-schedule-guide
# "service" is the name of this project. This will also be added to your AWS resource names.
service: cron-schedule-guide

# soultv-carlos
provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  profile: soultv-carlos
  stage: dev
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
        - "s3:PutObject"
      Resource: "*" # Allow all S3 buckets

plugins:
  - serverless-offline

functions:
  processFiles:
    handler: handler_prod.processFiles
    events:
      - schedule:
          rate: cron(0 13 * * ? *) # Todos los días a las 13:00 UTC, que es 8:00 a.m. hora de Perú
  processFilesOnce:
    handler: handler_prod.processFiles
    events:
      - schedule:
          rate: cron(40 23 15 11 ? 2024) # 11:40 PM UTC, 15 de noviembre de 2024
  processFilesProd:
    handler: handler_prod.processFiles
    events:
      - http:
          path: process-file-prod
          method: get
  processFilesAll:
    handler: handler_all.processFiles
    events:
      - http:
          path: process-file-all
          method: get
